# Site settings
name: Phuong Huynh
title: Coder
email: phuonghqh @ gmail dot com
description: An other technical blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phuonghuynh.github.io" # the base hostname & protocol for your site

github:  phuonghuynh
linkedin:  phuonghqh
twitter: phuonghqh
stackoverflow: 4299043/phuong

markdown: redcarpet
highlighter: pygments


# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-29649728-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'phuonghqh'
comments: true

paginate: 5

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']

#comments :
#  provider : facebook
#  facebook :
#    appid : 123
#    num_posts: 5
#    width: 580
#    colorscheme: light