# Site settings
name: An other technical blog
title: Phuong H
email: phuonghqh at gmail
description: > # this means to ignore newlines until "baseurl:"
  Another technical blog<br />E: phuonghqh at gmail
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phuonghuynh.github.io" # the base hostname & protocol for your site
github:  phuonghuynh

markdown: redcarpet
highlighter: pygments


# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

paginate: 10

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
